### PR TITLE
HSLdevcom/bultti#385 Highlight preview JOLA equipment defect rows tha…

### PR DESCRIPTION
**Pull request by danieldunderfelt**
Closes HSLdevcom/bultti#385

Highlight JOLA rows that lead to sanctions in the equipment defect preview.

Server PR: https://github.com/HSLdevcom/bultti/pull/423/files

### CODE REVIEW

**Comment by Divinare** [comment]
Btw why is this row being highlighted as red?

Asetuspvm    Eräpäivä       Lopetuspäivä
highlighted_jola_row

Isn't it OK if it has been repaired at the same date as deadline is?

EDIT: I know the answer...

Method: isAfter() has this line:
```
return checkVal >= otherVal
```
as it should be checkVal > otherVal? So isAfter shouldn't be used here?

**Comment by danieldunderfelt** [comment]
> Btw why is this row being highlighted as red?
> 
> Asetuspvm Eräpäivä Lopetuspäivä
> highlighted_jola_row
> 
> Isn't it OK if it has been repaired at the same date as deadline is?
> 
> EDIT: I know the answer...
> 
> Method: isAfter() has this line:
> 
> ```
> return checkVal >= otherVal
> ```
> 
> as it should be checkVal > otherVal? So isAfter shouldn't be used here?

Good catch, I'll fix this.

**Comment by danieldunderfelt** [comment]
Fixed!

**Review by Divinare — APPROVED** [review]
LGTM!

**Pull request merged**
